import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import LoginPage from '../pages/login'


export default function Home() {
    return (
        <LoginPage/>
        /*
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <h1> Bonjour  </h1>
            </Head>

            <main>
                <h1> Nouvelle page d'accueil </h1>
            </main>

            <footer>
            </footer>
        </div>
    */
        )
}
